// --- 1. FIREBASE INITIALIZATION ---
const firebaseConfig = { apiKey: "AIzaSyBwEf91Cf0m13JX0uIipIO1GwAOFR1tFD8", authDomain: "our-grocery-app.firebaseapp.com", projectId: "our-grocery-app", storageBucket: "our-grocery-app.appspot.com", messagingSenderId: "885212081182", appId: "1:885212081182:web:525e03a5d9ba7613be520f" };
firebase.initializeApp(firebaseConfig);
const auth = firebase.auth();
const db = firebase.firestore();

// --- 2. DOM ELEMENT REFERENCES ---
const loginButton = document.getElementById('login-button'), unauthorizedLogoutButton = document.getElementById('unauthorized-logout-button'), logoutButton = document.getElementById('logout-button'), userNameSpan = document.getElementById('user-name'), listTitle = document.getElementById('list-title'), shoppingModeToggle = document.getElementById('shopping-mode-toggle'), itemNameInput = document.getElementById('item-name-input'), itemQuantityInput = document.getElementById('item-quantity-input'), itemNotesInput = document.getElementById('item-notes-input'), saveFavoriteCheckbox = document.getElementById('save-favorite-checkbox'), addButton = document.getElementById('add-button'), addButtonText = document.getElementById('add-button-text'), completeListButton = document.getElementById('complete-list-button'), shoppingListUl = document.getElementById('shopping-list-ul'), completedListUl = document.getElementById('completed-list-ul'), lookLaterSection = document.getElementById('look-later-section'), lookLaterListUl = document.getElementById('look-later-list-ul'), pastListsUl = document.getElementById('past-lists-ul'), favoritesContainer = document.getElementById('favorites-container'), favoritesCategoryTabs = document.getElementById('favorites-category-tabs'), manageFavoritesButton = document.getElementById('manage-favorites-button'), favoritesModalOverlay = document.getElementById('favorites-modal-overlay'), closeModalButton = document.getElementById('close-modal-button'), modalFavoritesList = document.getElementById('modal-favorites-list'), newCategoryInput = document.getElementById('new-category-input'), addCategoryButton = document.getElementById('add-category-button');

// --- 3. GLOBAL STATE MANAGEMENT ---
let activeListId = null, unsubscribeFromItems = null, unsubscribeFromLists = null, unsubscribeFromFavorites = null, unsubscribeFromCategories = null;
let favoritesCache = [], categoriesCache = [], editingFavoriteId = null;
let activeCategoryId = 'all';

// --- 4. CORE LOGIC FUNCTIONS ---
function formatDate(timestamp) { if (!timestamp) return '...'; return new Date(timestamp.seconds * 1000).toLocaleDateString("el-GR", { day: 'numeric', month: 'long', year: 'numeric' }); }
function loadList(listDoc) { activeListId = listDoc.id; listTitle.textContent = `Λίστα: ${formatDate(listDoc.data().createdAt)}`; if (unsubscribeFromItems) unsubscribeFromItems(); const itemsRef = db.collection('lists').doc(activeListId).collection('items'); unsubscribeFromItems = itemsRef.orderBy('name').onSnapshot(snapshot => { shoppingListUl.innerHTML = ''; completedListUl.innerHTML = ''; lookLaterListUl.innerHTML = ''; snapshot.forEach(doc => { const item = doc.data(); const id = doc.id; const li = document.createElement('li'); li.innerHTML = `<input type="checkbox" class="item-checkbox" data-id="${id}" ${item.status === 'completed' ? 'checked' : ''}><div class="item-content"><div class="item-name">${item.name}</div><div class="item-details">${item.quantity ? `<span class="quantity">${item.quantity}</span>` : ''}${item.notes ? `<span class="notes">${item.notes}</span>` : ''}</div></div><button class="cant-find-button" data-id="${id}">?</button><button class="delete-button" data-id="${id}">&times;</button>`; if (item.status === 'completed') { completedListUl.appendChild(li); } else if (item.status === 'later') { lookLaterListUl.appendChild(li); } else { shoppingListUl.appendChild(li); } }); lookLaterSection.classList.toggle('empty', lookLaterListUl.children.length === 0); }); }
async function createNewList() { console.log("Creating a new list..."); shoppingListUl.innerHTML = '<li>Δημιουργία νέας λίστας...</li>'; completedListUl.innerHTML = ''; const newList = { createdAt: firebase.firestore.FieldValue.serverTimestamp(), isActive: true, completedAt: null }; const newListRef = await db.collection('lists').add(newList); const newListDoc = await newListRef.get(); loadList(newListDoc); }
function resetAddItemForm() { itemNameInput.value = ''; itemQuantityInput.value = ''; itemNotesInput.value = ''; saveFavoriteCheckbox.checked = false; editingFavoriteId = null; addButtonText.textContent = 'Προσθήκη στη Λίστα'; saveFavoriteCheckbox.parentElement.style.display = 'flex'; itemNameInput.focus(); }
function addItemOrUpdateFavorite() { const itemName = itemNameInput.value.trim(); if (!itemName) return; const itemQuantity = itemQuantityInput.value.trim(); const itemNotes = itemNotesInput.value.trim(); if (editingFavoriteId) { db.collection('favorites').doc(editingFavoriteId).set({ name: itemName, quantity: itemQuantity, notes: itemNotes, categoryId: categoriesCache.find(c => c.name.toLowerCase() === itemName.toLowerCase())?.id || null }).then(() => { resetAddItemForm(); }); return; } if (activeListId) { db.collection('lists').doc(activeListId).collection('items').add({ name: itemName, quantity: itemQuantity, notes: itemNotes, status: 'pending' }); } if (saveFavoriteCheckbox.checked) { const favoriteId = itemName.toLowerCase(); db.collection('favorites').doc(favoriteId).set({ name: itemName, quantity: itemQuantity, notes: itemNotes, categoryId: null }, { merge: true }); } resetAddItemForm(); }
function renderFavorites() { favoritesCategoryTabs.innerHTML = ''; const allTab = document.createElement('button'); allTab.className = 'category-tab'; allTab.textContent = 'Όλα'; allTab.dataset.id = 'all'; if ('all' === activeCategoryId) allTab.classList.add('active'); favoritesCategoryTabs.appendChild(allTab); const noCategoryTab = document.createElement('button'); noCategoryTab.className = 'category-tab'; noCategoryTab.textContent = 'Χωρίς Κατηγορία'; noCategoryTab.dataset.id = 'none'; if ('none' === activeCategoryId) noCategoryTab.classList.add('active'); favoritesCategoryTabs.appendChild(noCategoryTab); categoriesCache.forEach(cat => { const tab = document.createElement('button'); tab.className = 'category-tab'; tab.textContent = cat.name; tab.dataset.id = cat.id; if (cat.id === activeCategoryId) tab.classList.add('active'); favoritesCategoryTabs.appendChild(tab); }); favoritesContainer.innerHTML = ''; const filteredFavorites = favoritesCache.filter(fav => { if (activeCategoryId === 'all') return true; if (activeCategoryId === 'none') return !fav.categoryId; return fav.categoryId === activeCategoryId; }); filteredFavorites.forEach(fav => { const button = document.createElement('button'); button.className = 'favorite-button'; button.textContent = fav.name; button.dataset.id = fav.id; favoritesContainer.appendChild(button); }); }
function openFavoritesModal() { modalFavoritesList.innerHTML = ''; favoritesCache.forEach(fav => { const li = document.createElement('li'); let optionsHtml = `<option value="">-- Επιλογή --</option>`; categoriesCache.forEach(cat => { optionsHtml += `<option value="${cat.id}" ${fav.categoryId === cat.id ? 'selected' : ''}>${cat.name}</option>`; }); li.innerHTML = `<span class="item-content">${fav.name}</span><div class="item-actions"><select class="modal-category-select" data-id="${fav.id}">${optionsHtml}</select><div class="modal-actions"><button class="modal-edit-btn" data-id="${fav.id}">Επεξεργασία</button><button class="modal-delete-btn" data-id="${fav.id}">Διαγραφή</button></div></div>`; modalFavoritesList.appendChild(li); }); favoritesModalOverlay.style.display = 'block'; }
function closeFavoritesModal() { favoritesModalOverlay.style.display = 'none'; if (editingFavoriteId) { resetAddItemForm(); } }
function handleListClick(e) { const target = e.target; if (!activeListId || !target.dataset.id) return; const itemsRef = db.collection('lists').doc(activeListId).collection('items'); const id = target.dataset.id; if (target.classList.contains('item-checkbox')) { const newStatus = target.checked ? 'completed' : 'pending'; itemsRef.doc(id).update({ status: newStatus }); } if (target.classList.contains('delete-button')) { if (confirm(`Είστε σίγουροι ότι θέλετε να διαγράψετε αυτό το προϊόν;`)) { itemsRef.doc(id).delete(); } } if (target.classList.contains('cant-find-button')) { itemsRef.doc(id).update({ status: 'later' }); } }

// --- 5. EVENT LISTENERS SETUP ---
shoppingModeToggle.addEventListener('change', () => { document.body.classList.toggle('shopping-mode', shoppingModeToggle.checked); });
addButton.addEventListener('click', addItemOrUpdateFavorite);
itemNameInput.addEventListener('keyup', (e) => { if (e.key === 'Enter') addItemOrUpdateFavorite(); });
shoppingListUl.addEventListener('click', handleListClick); completedListUl.addEventListener('click', handleListClick); lookLaterListUl.addEventListener('click', handleListClick);
completeListButton.addEventListener('click', async () => { if (!activeListId || !confirm('Είστε σίγουροι ότι θέλετε να ολοκληρώσετε αυτή τη λίστα;')) return; const currentListRef = db.collection('lists').doc(activeListId); await currentListRef.update({ isActive: false, completedAt: firebase.firestore.FieldValue.serverTimestamp() }); if (unsubscribeFromItems) unsubscribeFromItems(); activeListId = null; shoppingListUl.innerHTML = ''; completedListUl.innerHTML = ''; lookLaterListUl.innerHTML = ''; await createNewList(); });
favoritesCategoryTabs.addEventListener('click', (e) => { if (e.target.classList.contains('category-tab')) { activeCategoryId = e.target.dataset.id; renderFavorites(); } });
favoritesContainer.addEventListener('click', (e) => { if (e.target.classList.contains('favorite-button')) { const favoriteId = e.target.dataset.id; const favoriteData = favoritesCache.find(fav => fav.id === favoriteId); if (favoriteData) { itemNameInput.value = favoriteData.name || ''; itemQuantityInput.value = favoriteData.quantity || ''; itemNotesInput.value = favoriteData.notes || ''; itemNameInput.focus(); } } });
manageFavoritesButton.addEventListener('click', openFavoritesModal); closeModalButton.addEventListener('click', closeFavoritesModal);
favoritesModalOverlay.addEventListener('click', (e) => { if (e.target === favoritesModalOverlay) closeFavoritesModal(); });
// THE FIX IS HERE: This listener was missing
addCategoryButton.addEventListener('click', () => {
    const categoryName = newCategoryInput.value.trim();
    if (categoryName) {
        // Use the name as the ID for simplicity and to prevent duplicates
        const categoryId = categoryName.toLowerCase();
        db.collection('categories').doc(categoryId).set({ name: categoryName })
            .then(() => {
                console.log("Category added!");
                newCategoryInput.value = '';
            })
            .catch(error => console.error("Error adding category: ", error));
    }
});
modalFavoritesList.addEventListener('change', (e) => { if (e.target.classList.contains('modal-category-select')) { const favoriteId = e.target.dataset.id; const categoryId = e.target.value; db.collection('favorites').doc(favoriteId).update({ categoryId: categoryId || null }); } });
modalFavoritesList.addEventListener('click', (e) => { const target = e.target; const favoriteId = target.dataset.id; if (!favoriteId) return; if (target.classList.contains('modal-edit-btn')) { const favoriteData = favoritesCache.find(fav => fav.id === favoriteId); if (favoriteData) { itemNameInput.value = favoriteData.name || ''; itemQuantityInput.value = favoriteData.quantity || ''; itemNotesInput.value = favoriteData.notes || ''; editingFavoriteId = favoriteId; addButtonText.textContent = 'Ενημέρωση Αγαπημένου'; saveFavoriteCheckbox.parentElement.style.display = 'none'; closeFavoritesModal(); itemNameInput.focus(); } } if (target.classList.contains('modal-delete-btn')) { const favoriteData = favoritesCache.find(fav => fav.id === favoriteId); if (confirm(`Είστε σίγουροι ότι θέλετε να διαγράψετε το "${favoriteData.name}" από τα αγαπημένα;`)) { db.collection('favorites').doc(favoriteId).delete(); } } });
pastListsUl.addEventListener('click', async (e) => { if (!e.target.classList.contains('past-list-header')) return; const header = e.target; const listId = header.dataset.id; const itemsUl = header.nextElementSibling; header.classList.toggle('open'); const isOpen = header.classList.contains('open'); if (isOpen && itemsUl.children.length === 0) { itemsUl.innerHTML = '<li>Φόρτωση...</li>'; const itemsSnapshot = await db.collection('lists').doc(listId).collection('items').orderBy('name').get(); itemsUl.innerHTML = ''; itemsSnapshot.forEach(doc => { const item = doc.data(); const itemLi = document.createElement('li'); itemLi.textContent = `${item.name}${item.quantity ? ` (${item.quantity})` : ''}${item.notes ? ` - ${item.notes}` : ''}`; if (item.status === 'completed') { itemLi.classList.add('completed-item'); } itemsUl.appendChild(itemLi); }); } itemsUl.style.display = isOpen ? 'block' : 'none'; });
loginButton.addEventListener('click', () => auth.signInWithPopup(new firebase.auth.GoogleAuthProvider()));

// --- 6. MAIN AUTHENTICATION CONTROLLER ---
auth.onAuthStateChanged(user => { if (user) { const userDocRef = db.collection('allowedUsers').doc(user.uid); userDocRef.get().then((doc) => { if (doc.exists) { document.body.classList.add('logged-in'); userNameSpan.textContent = user.displayName; logoutButton.onclick = () => auth.signOut(); db.collection('lists').where('isActive', '==', true).limit(1).get().then(snapshot => { snapshot.empty ? createNewList() : loadList(snapshot.docs[0]); }); if (unsubscribeFromLists) unsubscribeFromLists(); unsubscribeFromLists = db.collection('lists').where('isActive', '==', false).orderBy('completedAt', 'desc').limit(10).onSnapshot(snapshot => { pastListsUl.innerHTML = ''; snapshot.forEach(doc => { const li = document.createElement('li'); li.innerHTML = `<div class="past-list-header" data-id="${doc.id}">Λίστα της ${formatDate(doc.data().completedAt)}</div><ul class="past-list-items"></ul>`; pastListsUl.appendChild(li); }); }); if (unsubscribeFromCategories) unsubscribeFromCategories(); unsubscribeFromCategories = db.collection('categories').orderBy('name').onSnapshot(snapshot => { categoriesCache = snapshot.docs.map(cat => ({ id: cat.id, ...cat.data() })); renderFavorites(); }); if (unsubscribeFromFavorites) unsubscribeFromFavorites(); unsubscribeFromFavorites = db.collection('favorites').orderBy('name').onSnapshot(snapshot => { favoritesCache = snapshot.docs.map(fav => ({ id: fav.id, ...fav.data() })); renderFavorites(); if (favoritesModalOverlay.style.display === 'block') { openFavoritesModal(); } }); } else { document.getElementById('login-section').style.display = 'none'; document.getElementById('unauthorized-section').style.display = 'block'; unauthorizedLogoutButton.onclick = () => auth.signOut(); } }); } else { shoppingModeToggle.checked = false; document.body.classList.remove('shopping-mode'); document.body.classList.remove('logged-in'); document.getElementById('login-section').style.display = 'block'; document.getElementById('unauthorized-section').style.display = 'none'; if (unsubscribeFromItems) unsubscribeFromItems(); if (unsubscribeFromLists) unsubscribeFromLists(); if (unsubscribeFromFavorites) unsubscribeFromFavorites(); if (unsubscribeFromCategories) unsubscribeFromCategories(); activeListId = null; } });

// --- 7. PWA SERVICE WORKER REGISTRATION ---
if ('serviceWorker' in navigator) { window.addEventListener('load', () => { navigator.serviceWorker.register('./sw.js').then(reg => console.log('SW registered.')).catch(err => console.log('SW registration failed: ', err)); }); }